/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\hero-model.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function HeroModel(props) {
  const { nodes, materials } = useGLTF("/3d-models/hero-model.glb");
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={
          nodes["tripo_node_de516345-d894-4e1c-8e72-a7891e93a9c7"].geometry
        }
        material={
          materials["tripo_material_de516345-d894-4e1c-8e72-a7891e93a9c7"]
        }
      />
    </group>
  );
}

useGLTF.preload("/hero-model.glb");
