export { default as AboutSection } from "./AboutSection";
export { default as TimelineSection } from "./TimelineSection";
export { default as ContactSection } from "./ContactSection";
export { default as ProjectsCountSection } from "./ProjectsCountSection";
export { default as FeaturedProjectsSection } from "./FeaturedProjectsSection";
export { default as SkillsSection } from "./SkillsSection";
export { default as HeroSection } from "./HeroSection";
export { default as VideosFeaturedProjectsSection } from "./VideosFeaturedProjectsSection";
export { default as DesignsFeaturedProjectsSection } from "./DesignsFeaturedProjectsSection";
