/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\public\3d-models\Zues.glb 
*/

import React from "react";
import { useGLTF } from "@react-three/drei";

export function ZuesModel(props) {
  const { nodes, materials } = useGLTF("/3d-models/Zues.glb");
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.mesh_0.geometry} material={nodes.mesh_0.material} />
    </group>
  );
}

useGLTF.preload("/3d-models/Zues.glb");
